FROM jenkins/jenkins:lts-jdk17

USER root

# Install docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Allow jenkins user to access docker
RUN usermod -aG docker jenkins

USER jenkins
